### ISSUE TITLE
CMR-Graphic sparse/dense bug

### ISSUE THREAD

**Issue by rolfvdhulst** [discopt/cmr#22]
When testing I found this weird case:
[temptestfile.sparse.txt](https://github.com/discopt/cmr/files/9289018/temptestfile.sparse.txt)

CMR-graphic concludes it is graphic, but the output is clearly wrong as it places all columns parallel in a cycle:
```
cmr-graphic -o dot temptestfile.sparse 

Read 4x5 matrix with 20 nonzeros in 0.000023 seconds.
Matrix IS graphic.
graph G {
 v_1 -- v_2 [label="r1",style=bold,color=red];
 v_10 -- v_1 [label="r2",style=bold,color=red];
 v_9 -- v_10 [label="r3",style=bold,color=red];
 v_13 -- v_9 [label="r4",style=bold,color=red];
 v_2 -- v_13 [label="c1"];
 v_2 -- v_13 [label="c2"];
 v_2 -- v_13 [label="c3"];
 v_2 -- v_13 [label="c4"];
 v_2 -- v_13 [label="c5"];
}
```
Ofcourse, I realized later that I forgot to add -i sparse to my command. However, the sparse matrix  being interpreted as a dense matrix is clearly quite not desirable; shouldn't it just crash?

**Comment by discopt** [comment]
First, it should not report that it is graphic, because the (beginning of the) file, interpreted as a dense matrix, is
```
4 5
12 1 1 1 1
4 1 1 5 1
2 1 1 2 3
1 2 5 1 3
```
which is not even binary, so certainly not graphic. I can think of the following:

1. Stop for non-binary matrices (makes sense).
2. Stop after reading although the file was not read completely (makes sense).
3. Stop reading a dense (resp. sparse) matrix if the line with the first tokens does not contain just two (resp. three). This is clearly more effort since scanf() will not be able to tell this. What do you think, @rolfvdhulst

**Comment by rolfvdhulst** [comment]
I think All three suggestions would make sense. I would probably go with 1., provided that there are no users which rely on this behavior.
