### ISSUE TITLE
Clarification needed on CMRdecIsSum function

### ISSUE THREAD

**Issue by mkoeppe** [discopt/cmr#35]
What exactly are the plowerLeftNonzeros, pupperRightNonzeros supposed to return?

```
CMR_EXPORT
int CMRdecIsSum(
  CMR_DEC* dec,             /**< Decomposition node. */
  bool* plowerLeftNonzeros, /**< Pointer for storing the lower-left submatrix of a 2- or 3-sum contains a nonzero (may be \c NULL). */
  bool* pupperRightNonzeros /**< Pointer for storing the lower-left submatrix of a 2- or 3-sum contains a nonzero (may be \c NULL). */
);

```

**Comment by discopt** [comment]
Does the changes in https://github.com/discopt/cmr/commit/96ff0881ad47cbb1c0933a7c02042cfbd34fe4ae clarify their meaning?

**Comment by mkoeppe** [comment]
Thank you, that's very helpful! 

@xuluze @jsantillan3 – is this all the data that we need for roundtripping 2-sums, 3-sums?

**Comment by mkoeppe** [comment]
(I think we were looking for an API function that would give a CMR_SEPA of a CMR_DEC)

**Comment by jsantillan3** [comment]
I think we want the marker information that CMRtwosum and CMRthreesum would need to take in to reproduce the parent matrix's block matrix form representation produced by k-sums from the child matrices. I don't really understand how the locations of nonzeroes on the upper left and upper right would give us that information, or if CMR_SEPA would store that somehow.

**Comment by xuluze** [comment]
> 

To add on Javier's comments, I am wondering if these boolean pointers will help us decide the position of the zero block (whether in the lower-left or upper-right) in the 2-sum. While in 3-sum, both blocks will be nonzero. Thank you!

**Comment by discopt** [comment]
I see. I think this is not implemented yet (but I have to look into it in detail because I don't recall exactly), but I fully agree that this would be useful. Generally speaking, all the information that you would need to restore the labeled parent matrix assuming that you have the labeled child matrix.

One more remark: a 3-sum may also have a zero block, in which case the other block would be rank 2.

**Comment by discopt** [comment]
For a k-sum with k >= 2 there is no mapping from rows/columns of a decomposition node to a child's rows/columns since there are (k-1) rows and (k-1) columns that belong to both children. Indeed, there is a CMR-internal data structure `CMR_SEPA` that contains this information, but I'm not sure whether a public interface would be a good idea. A "workaround" would be to query each child and use `CMRdecRowsParent` & friends to ask for the mapping from child rows/columns to parent rows/columns.
